### ISSUE TITLE
Não envia emails SMTP

### ISSUE THREAD

**Issue by EduVillas** [velhobit/PortilloMail#1]
![conf](https://user-images.githubusercontent.com/5814770/29642006-b57b1e62-883c-11e7-8400-973097d178be.jpg)
Erro ao enviar teste:
Não foi possivel ....

Erro ao enviar o email:
Warning: stream_socket_enable_crypto(): Peer certificate CN=`*.uni5.net' did not match expected CN=`smtp.meudominio.com.br' in /home/pasta do script/portillo/libs/phpmail/class.smtp.php on line 343

**Comment by velhobit** [comment]
Essa falha é causada porque o PHP 5.6 + verifica a autenticidade do SSL antes de enviar. Ele não está reconhecendo o SSL com a determinada URL. 

Dê um olhada aqui e deve resolver o problema https://stackoverflow.com/questions/30371910/phpmailer-generates-php-warning-stream-socket-enable-crypto-peer-certificate
